version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    networks:
      new:
        aliases:
          - database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - ./database/migrations:/migrations
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable",
      "up"
    ]
    depends_on:
      - postgres

  bot:
    build:
      context: ./
      dockerfile: docker/Dockerfile.HotReload
    networks:
      - new
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app/

networks:
  new: