FROM golang:1.18-alpine

ENV GO111MODULE=on

WORKDIR /app/
COPY ./ /app/
RUN go mod download
RUN go install -mod=mod github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build main.go" --command=./main